export const AVAILABLE_SPECIALTIES = [
  'Athletiktraining',
  'Body-Transformation',
  'Ernährungsberatung',
  'Fettabbau',
  'Functional Fitness',
  'Functional Training',
  'Gewichtsmanagement',
  'Gewichtsverlust',
  'Ganzkörpertraining',
  'Gesundheitsorientiertes Krafttraining',
  'HIIT & Cardio',
  'Hypertrophie',
  'Körperhaltung & Core',
  'Krafttraining',
  'Leistungsdiagnostik',
  'Lauftraining & Ausdauer',
  'Mobilität',
  'Mobility & Stretching',
  'Muskelaufbau',
  'Postnatales Training',
  'Pränatales Training',
  'Reha & Prävention',
  'Rehabilitation',
  'Rückentraining',
  'Seniorenfitness',
  'Stoffwechseloptimierung',
  'Stressabbau & Entspannung',
  'Sportartspezifisches Training',
  'Transformation',
  'Yogalates & Core',
].sort((a, b) => a.localeCompare(b, 'de'));

export const QUIZ_GOAL_BLOCKS = [
  { category: 'Hypertrophie & Muskelaufbau', items: ['Muskelaufbau', 'Hypertrophie', 'Krafttraining'] },
  { category: 'Gewichtsverlust & Transformation', items: ['Gewichtsverlust', 'Fettabbau', 'Body-Transformation', 'Ernährungsberatung'] },
  { category: 'Gesundheit & Prävention', items: ['Rückentraining', 'Rehabilitation', 'Reha & Prävention', 'Mobilität', 'Mobility & Stretching'] },
  { category: 'Performance & Athletik', items: ['Leistungsdiagnostik', 'Athletiktraining', 'Ausdauer', 'Functional Fitness', 'Functional Training'] },
];
